language: go

go:
  - 1.13.x

before_install:
  - curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s -- -b $(go env GOPATH)/bin v1.21.0

script:
  - golangci-lint run --timeout 50s
  - go test -v ./...
